name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 24

      - name: Install required things
        run: |
          npm ci
          npm install -g @angular/cli

      - name: Build app
        run: |
          cp src/environment/environment.production.ts src/environment/environment.ts
          npx nx build --configuration production

      - name: Upload new files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/schutters-app/
          dangerous-clean-slate: true
          protocol: ftps
          timeout: 60000
